import Classification from "./classification.type";

export default interface Topic {
  id: number;
  name: string;
  description: string;
  editor_label: string;
  user_count: number;
  slug: string;
  start_date: string;
  end_date: string;
  chart_time_unit: string;
  timepoint_day_interval: number;
  articles_count: number;
  articles_count_delta: number;
  attributed_articles_created_delta: number;
  attributed_length_delta: number;
  attributed_revisions_count_delta: number;
  attributed_token_count: number;
  average_wp10_prediction: number;
  wp10_prediction_categories: object;
  length: number;
  length_delta: number;
  revisions_count: number;
  revisions_count_delta: number;
  timepoints_count: number;
  token_count: number;
  token_count_delta: number;
  has_stats: boolean;
  has_analytics: boolean;
  data_updated_at: string | null;
  owned: boolean;
  users_csv_url: string;
  users_csv_filename: string;
  articles_csv_url: string;
  articles_csv_filename: string;
  timepoint_generate_job_id: string;
  users_import_job_id: string;
  article_import_job_id: string;
  timepoint_generate_percent_complete: number;
  generate_article_analytics_status: string;
  generate_article_analytics_percent_complete: number;
  generate_article_analytics_articles_fetched: number;
  generate_article_analytics_articles_total: number;
  generate_article_analytics_skipped: number;
  articles_import_percent_complete: number;
  users_import_percent_complete: number;
  articles_import_status: string;
  timepoint_generate_status: string;
  users_import_status: string;
  incremental_topic_build_status: string;
  incremental_topic_build_percent_complete: number;
  generate_article_analytics_message: string;
  incremental_topic_build_stage_message: string;
  incremental_topic_build_stage: string | null;
  incremental_topic_build_message: string;
  incremental_topic_build_at: number | null;
  incremental_topic_build_total: number | null;
  incremental_topic_build_timestamps_done: number | null;
  incremental_topic_build_timestamps_total: number | null;
  timepoint_generate_message: string;
  classifications: Array<Classification>;
  convert_tokens_to_words: boolean;
  tokens_per_word: number;
  tokens_per_word_effective: number;
  tokens_per_word_default: number | null;
  tb_handle: string | null;
  users_import_started_at: number | null;
  articles_import_started_at: number | null;
  generate_article_analytics_started_at: number | null;
  incremental_topic_build_started_at: number | null;
  timepoint_generate_started_at: number | null;
  data_generation_state: "idle" | "running" | "complete";
}
